[ignore]
directories = [".git", "node_modules", "venv"]
files = ["anyrandomfile"]

[ollama]
model = 'llama3.2'
stream = false
base_prompt = "Explain the following code and its working. Ignore all the extra stuff and just focus on explaining this code in parts as code snippet and then explanation. Here's the code:"

